version: '3.8'

services:
  scraper:
    build: 
      context: .
      dockerfile: ./Dockerfile.scraper
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=newsdb
      - DB_USER=devuser
      - DB_PASSWORD=devpassword
      - SCRAPE_INTERVAL=3600  # in seconds
      - ENV=development
    depends_on:
      - db
    restart: no
    volumes:
      - ./src:/app/src  # Mount local directory for development
      - ./output:/app/output  # Mount output directory for development

  production:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=newsdb
      - DB_USER=devuser
      - DB_PASSWORD=devpassword
      - SCRAPE_INTERVAL=3600  # in seconds
      - ENV=production
      - BLENDER_FILEPATH=/usr/local/bin/blender
      - OUTPUT_FILEPATH=/app/output
      - ASSETS_FILEPATH=/app/src/assets
    depends_on:
      - db
    restart: no
    volumes:
      - ./src:/app/src  # Mount local directory for development
      - ./output:/app/output  # Mount output directory for development

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=newsdb
    ports:
      - "5432:5432"  # Expose port for local development
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
